### ISSUE TITLE
Problem with mapper dependency.

### ISSUE THREAD

**Issue by smeyerhot** [tohtsky/myFM#1]
The mapper library doesn't seem to have any type DefaultMapper...

```
ImportError                               Traceback (most recent call last)
<ipython-input-9-46b0ef8584af> in <module>
      6 import pandas as pd
      7 from scipy import sparse as sps
----> 8 from mapper import DefaultMapper
      9 # read movielens 1m data.
     10 from myfm.utils.benchmark_data import MovieLens1MDataManager

ImportError: cannot import name 'DefaultMapper' from 'mapper'
```

**Comment by tohtsky** [comment]
Hi, @smeyerhot!

Thank you for pointing out the problem!
You are referring to `examples/ml-1m-extended.ipynb`, right?
Indeed I forgot to replace the API change in the example, and updated the notebook.
Could you try again with the newer version of the notebook or its script version `examples/ml-1m-regression.py`?

**Comment by smeyerhot** [comment]
Hey, @tohtsky 

Thanks for addressing this. I am working through your code right now. Great stuff!

**Comment by smeyerhot** [comment]
All set after update
