### ISSUE TITLE
TypeError: 'CategoryValueToSparseEncoder' object is not subscriptable

### ISSUE THREAD

**Issue by 1170801121** [tohtsky/myFM#13]
Hi, when I run 'python ml-100k-regression.py 1', the bug traceback is as follows:
df_train.shape = (80000, 4), df_test.shape = (20000, 4)
Traceback (most recent call last):
  File "ml-100k-regression.py", line 233, in <module>
    target.append(RelationBlock(user_map, augment_user_id(unique_users)))
  File "ml-100k-regression.py", line 189, in augment_user_id
    col.append(movie_to_internal[mid])
TypeError: 'CategoryValueToSparseEncoder' object is not subscriptable

Can you give me some instructions on the bug?

**Comment by tohtsky** [comment]
Hi @1170801121, thank you for reporting the issue!
This is indeed a bug with the recent changes.

I'm fixing the degradation and will soon release a version with the bugs fixed.

**Comment by tohtsky** [comment]
Released a new version 0.3.5. Could you `pip install --upgrade myfm` and try the example again?
Thank you again for reporting the bug!

**Comment by 1170801121** [comment]
Great, the bug is addressed now! Thank you for the quick solution!
