### ISSUE TITLE
Could we reconstruct the matrix (same dimensions) with the feature embedding ?

### ISSUE THREAD

**Issue by wanglu2014** [tohtsky/myFM#7]
We factorize a matrix into factors, could we reconstruct a matrix based on factors.

**Comment by tohtsky** [comment]
> could we reconstruct a matrix based on factors

I think so, but I don't think it has anything to do with factorization machines (and other algorithms based on explicit feedback).
You might want to consult the literature on SVD or something similar (depending on what you want to do).
